gmail_username: 'verbandkirchlichermmitarbeiter@gmail.com'
gmail_password: '.bEaQd.3BX'
salt: "N\xE3(Vh\xE3q\x1C\\sj\x8F\x15\xF3Zf=\xE4\xBD\x03\xB2\xF7\xF5\x031\xD1\x03\xBC#\xC1\x06))\xCB\x81\xny\xD9\x9D\xB0\xFB7Z\xF8+@\xD5=\xCD8$\x1E\xC1\x96Q\x96!\xDE2Z\xEDL\xF9\xF0"
key: "<\xE4i\x8BB\xD1[\x98{\x9F\xDE1\xC6u\x06\xFC\xF8!\xC6\xED\xFEh\xAF\xF5\xA2\xE8\xC6jy,\x19/1\xBB\xEE\x9Es\xA3(\x971\xD3\xBFR!8\x13\xB8\xCDV\xD7\x03\xC8R@v\xF5.\xCF\xBAA\x890\xD8"